package api

import (
	"github.com/gin-gonic/gin"

	"speed-inventory-management/backend/internal/service"
)

func (s *Server) registerStaffRoutes(protected gin.IRouter) {
	staff := protected.Group("")
	staff.Use(s.requireRoles(service.RoleAdmin, service.RoleOperator, service.RoleViewer))
	staff.GET("/dashboard", s.handleDashboard)
	staff.GET("/billing/settings", s.handleGetBillingInvoiceSettings)
	staff.GET("/customers", s.handleListCustomers)
	staff.GET("/locations", s.handleListLocations)
	staff.GET("/sku-master", s.handleListSKUMasters)
	staff.GET("/outbound-source-references", s.handleListOutboundSourceReferences)
	staff.GET("/items", s.handleListItems)
	staff.GET("/movements", s.handleListMovements)
	staff.GET("/reports/operations", s.handleOperationsReport)
	staff.GET("/reports/sku-flow", s.handleSKUFlowReport)
	staff.GET("/outbound-documents", s.handleListOutboundDocuments)
	staff.GET("/inbound-documents", s.handleListInboundDocuments)
	staff.GET("/bulk-import-batches", s.handleListBulkImportBatches)
	staff.GET("/bulk-import-batches/:id/file", s.handleDownloadBulkImportBatchFile)
	staff.GET("/outbound-documents/:id/attachments/:attachmentId/download-url", s.handleGetOutboundDocumentAttachmentDownloadURL)
	staff.GET("/inbound-documents/:id/attachments/:attachmentId/download-url", s.handleGetInboundDocumentAttachmentDownloadURL)
	staff.GET("/adjustments", s.handleListInventoryAdjustments)
	staff.GET("/transfers", s.handleListInventoryTransfers)
	staff.GET("/cycle-counts", s.handleListCycleCounts)
	staff.GET("/container-lifecycle-events", s.handleListContainerLifecycleEvents)
	staff.POST("/billing/preview", s.handlePreviewBilling)
	staff.GET("/billing/invoices", s.handleListBillingInvoices)
	staff.GET("/billing/invoices/:id", s.handleGetBillingInvoice)

	operator := protected.Group("")
	operator.Use(s.requireRoles(service.RoleAdmin, service.RoleOperator))
	operator.POST("/outbound-documents", s.handleCreateOutboundDocument)
	operator.POST("/outbound-documents/bulk-import-preview", s.handlePreviewOutboundBulkImport)
	operator.POST("/outbound-documents/bulk-import-revalidate", s.handleRevalidateOutboundBulkImport)
	operator.POST("/outbound-documents/bulk-import-commit", s.handleCommitOutboundBulkImport)
	operator.POST("/outbound-documents/bulk-confirm", s.handleBulkConfirmOutboundDocuments)
	operator.POST("/outbound-documents/bulk-delete", s.handleBulkDeleteOutboundDocuments)
	operator.PUT("/outbound-documents/:id", s.handleUpdateOutboundDocument)
	operator.PUT("/outbound-documents/:id/document-note", s.handleUpdateOutboundDocumentNote)
	operator.POST("/outbound-documents/:id/confirm", s.handleConfirmOutboundDocument)
	operator.POST("/outbound-documents/:id/tracking-status", s.handleUpdateOutboundDocumentTrackingStatus)
	operator.POST("/outbound-documents/:id/cancel", s.handleCancelOutboundDocument)
	operator.POST("/outbound-documents/:id/copy", s.handleCopyOutboundDocument)
	operator.POST("/outbound-documents/:id/attachments", s.handleUploadOutboundDocumentAttachment)
	operator.DELETE("/outbound-documents/:id/attachments/:attachmentId", s.handleDeleteOutboundDocumentAttachment)
	operator.POST("/inbound-documents", s.handleCreateInboundDocument)
	operator.POST("/inbound-documents/import-preview", s.handleImportInboundDocumentPreview)
	operator.POST("/inbound-documents/bulk-import-preview", s.handlePreviewInboundBulkImport)
	operator.POST("/inbound-documents/bulk-import-revalidate", s.handleRevalidateInboundBulkImport)
	operator.POST("/inbound-documents/bulk-import-commit", s.handleCommitInboundBulkImport)
	operator.PUT("/inbound-documents/:id", s.handleUpdateInboundDocument)
	operator.PUT("/inbound-documents/:id/document-note", s.handleUpdateInboundDocumentNote)
	operator.PUT("/inbound-documents/:id/container-type", s.handleUpdateInboundDocumentContainerType)
	operator.POST("/inbound-documents/bulk-status", s.handleBulkUpdateInboundDocumentStatus)
	operator.POST("/inbound-documents/:id/confirm", s.handleConfirmInboundDocument)
	operator.POST("/inbound-documents/:id/tracking-status", s.handleUpdateInboundDocumentTrackingStatus)
	operator.POST("/inbound-documents/:id/cancel", s.handleCancelInboundDocument)
	operator.GET("/inbound-documents/:id/deletion-impact", s.handlePreviewInboundDeletion)
	operator.POST("/inbound-documents/:id/delete-with-dependencies", s.handleDeleteInboundWithDependencies)
	operator.POST("/inbound-documents/:id/copy", s.handleCopyInboundDocument)
	operator.POST("/inbound-documents/:id/attachments", s.handleUploadInboundDocumentAttachment)
	operator.DELETE("/inbound-documents/:id/attachments/:attachmentId", s.handleDeleteInboundDocumentAttachment)
	operator.POST("/adjustments", s.handleCreateInventoryAdjustment)
	operator.POST("/transfers", s.handleCreateInventoryTransfer)
	operator.POST("/transfers/bulk-import-preview", s.handlePreviewBulkTransferImport)
	operator.POST("/transfers/bulk-import-revalidate", s.handleRevalidateBulkTransferImport)
	operator.POST("/transfers/bulk-import-commit", s.handleCommitBulkTransferImport)
	operator.POST("/cycle-counts", s.handleCreateCycleCount)
	operator.POST("/billing/invoices", s.handleCreateBillingInvoice)
	operator.POST("/billing/invoices/generate", s.handleGenerateBillingInvoice)
	operator.PUT("/billing/invoices/:id", s.handleUpdateBillingInvoice)
	operator.POST("/billing/invoices/:id/lines", s.handleAddBillingInvoiceLine)
	operator.PUT("/billing/invoices/:id/lines/:lineId", s.handleUpdateBillingInvoiceLine)
	operator.DELETE("/billing/invoices/:id/lines/:lineId", s.handleDeleteBillingInvoiceLine)

	admin := protected.Group("")
	admin.Use(s.requireRoles(service.RoleAdmin))
	admin.POST("/customers", s.handleCreateCustomer)
	admin.PUT("/customers/:id", s.handleUpdateCustomer)
	admin.DELETE("/customers/:id", s.handleDeleteCustomer)
	admin.GET("/audit-logs", s.handleListAuditLogs)
	admin.GET("/users", s.handleListUsers)
	admin.POST("/users", s.handleCreateUser)
	admin.PUT("/users/:id/access", s.handleUpdateUserAccess)
	admin.PUT("/ui-preferences/:key", s.handleUpdateUIPreference)
	admin.PUT("/billing/settings", s.handleUpdateBillingInvoiceSettings)
	admin.POST("/locations", s.handleCreateLocation)
	admin.PUT("/locations/:id", s.handleUpdateLocation)
	admin.DELETE("/locations/:id", s.handleDeleteLocation)
	admin.POST("/sku-master", s.handleCreateSKUMaster)
	admin.PUT("/sku-master/:id", s.handleUpdateSKUMaster)
	admin.DELETE("/sku-master/:id", s.handleDeleteSKUMaster)
	admin.POST("/billing/invoices/:id/finalize", s.handleFinalizeBillingInvoice)
	admin.POST("/billing/invoices/:id/mark-paid", s.handleMarkBillingInvoicePaid)
	admin.POST("/billing/invoices/:id/void", s.handleVoidBillingInvoice)
	admin.DELETE("/billing/invoices/:id", s.handleDeleteBillingInvoice)
}
